import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import Footer from "@/components/footer";
import BrandLogo from "@/components/brand-logo";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of service for ReplyKit review reply drafting assistant.",
};

export default function TermsPage() {
  return (
    <main className="pricing-page">
      <nav className="landing-nav" aria-label="Main navigation">
        <Link className="brand" href="/">
          <BrandLogo size={32} />
          <span>replykit</span>
        </Link>
        <div className="landing-links">
          <Link href="/#how-it-works">How it works</Link>
          <Link href="/pricing">Pricing</Link>
          <Link className="quiet-button" href="/login">Sign in</Link>
        </div>
      </nav>

      <header className="pricing-hero">
        <Link className="pricing-back" href="/"><ArrowLeft size={13} /> Back to ReplyKit</Link>
        <div className="hero-kicker"><span /> Straightforward terms</div>
        <h1 className="pricing-title">Terms of Service.<br /><em>You stay in control.</em></h1>
        <p className="pricing-lede">
          ReplyKit generates drafts for you to review. You are always in control of what you publish.
        </p>
        <p style={{ marginTop: 12, fontSize: 12, color: "#8a948c" }}>
          Last updated: October 4, 2026
        </p>
      </header>

      <section className="pricing-faq" style={{ maxWidth: 860, margin: "20px auto 70px" }}>
        <div>
          <div className="eyebrow">Clear boundaries</div>
          <h2>Our agreement with you.</h2>
        </div>
        <div className="pricing-faq-list">
          <article>
            <h3>ReplyKit only drafts text</h3>
            <p>
              ReplyKit is an AI-powered drafting tool designed to assist business owners in crafting thoughtful review replies. ReplyKit does not automatically publish, sync with, or post replies to Google Maps, Google Business Profile, Yelp, TripAdvisor, or any other third-party review platform.
            </p>
          </article>

          <article>
            <h3>Rules on AI output and accuracy</h3>
            <p>
              Drafts are generated by artificial intelligence and may contain mistakes, inaccuracies, or hallucinations. You are solely responsible for reviewing and verifying all names, facts, offers, pricing, and policies before copying or publishing any draft.
            </p>
          </article>

          <article>
            <h3>Content ownership and processing license</h3>
            <p>
              You retain full ownership of all reviews, feedback, and text you provide. You grant ReplyKit a limited, non-exclusive license to process, format, and generate drafts from your content solely to deliver, secure, and maintain the service.
            </p>
          </article>

          <article>
            <h3>Beta service and changes</h3>
            <p>
              ReplyKit is currently provided as a free public beta on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. ReplyKit may change, suspend, or terminate the beta service at any time, with advance notice provided by email.
            </p>
          </article>

          <article>
            <h3>Limitation of liability</h3>
            <p>
              To the fullest extent permitted by applicable law, ReplyKit and its creators or operators will not be liable for any indirect, incidental, special, exemplary, consequential, or punitive damages, or loss of profits, goodwill, or business reputation arising out of or related to your use of the service or any customer replies posted.
            </p>
          </article>

          <article>
            <h3>Governing law and dispute resolution</h3>
            <p>
              These terms are governed by and construed in accordance with the laws of India. If you have questions, concerns, or legal disputes, contact us directly at <a className="text-link" href="mailto:tharannaidus1@gmail.com">tharannaidus1@gmail.com</a>.
            </p>
          </article>

          <article>
            <h3>Privacy</h3>
            <p>
              Please review our <Link className="text-link" href="/privacy">Privacy Policy</Link> for details on how we process and protect your account and review information.
            </p>
          </article>
        </div>
      </section>

      <Footer />
    </main>
  );
}
